#include <lib/nlang/runtime.h>
#define NLANG_DECLARE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_TYPES

#define NLANG_DECLARE_TYPES
# include "t00/fixme12.n.o.h"
#undef NLANG_DECLARE_TYPES
#ifndef HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#ifndef HAS0__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_

#ifndef HAS0__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#ifndef HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS0__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#ifndef HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define NLANG_DEFINE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_TYPES

#define NLANG_DEFINE_TYPES
# include "t00/fixme12.n.o.h"
#undef NLANG_DEFINE_TYPES

#define NLANG_DECLARE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#define NLANG_DECLARE_FUNCTIONS
# include "t00/fixme12.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS
#ifndef HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_
static nlang_builtins_void t00_fixme12_bar(_Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_ p);

#ifndef HAS2__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define NLANG_DEFINE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#define NLANG_DEFINE_FUNCTIONS
# include "t00/fixme12.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS
#ifndef HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_
static nlang_builtins_void t00_fixme12_bar(_Ngen_nlang_builtins_nullable_ref___Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN__genN_ p) {
 {
;;
}
}

#ifndef HAS3__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
typedef const _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
nlang_builtins_i32 _Nmain(void) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
 {
;;
nlang_builtins_i32 x= { 0 };
;
;
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym0 = ((&x));
;
_Ngen_nlang_builtins_ref___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ _Ngensym4 = ((&_Ngensym0));
;
t00_fixme12_bar(_Ngensym4);
_Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_ _Ngensym1 = ((&x));
;
_Ngen_nlang_builtins_ref___Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN__genN_ _Ngensym5 = ((&_Ngensym1));
;
t00_fixme12_bar(_Ngensym5);
nlang_builtins_i32 _Ngensym2 = (nlang_builtins_i32)0;
;
return _Ngensym2;
}
return _nretval;
}
void t00_fixme12_Nrunexamples(void) __attribute__((section(".text.nlang.examples")));
void t00_fixme12_Nrunexamples(void) {
}
