#include <lib/nlang/runtime.h>
#define NLANG_DECLARE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_TYPES

#define NLANG_DECLARE_TYPES
# include "t00/optional.n.o.h"
#undef NLANG_DECLARE_TYPES
#ifndef HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_

#ifndef HAS0__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#ifndef HAS0__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
struct _Ndyn__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
struct _Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ _Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS0__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
struct _Ndyn__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
struct _Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ _Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS0__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
#ifndef HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef const struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
;
#ifndef HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
;
#endif // HAS0__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_



#define NLANG_DEFINE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_TYPES

#define NLANG_DEFINE_TYPES
# include "t00/optional.n.o.h"
#undef NLANG_DEFINE_TYPES

#ifndef HAS1__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS1__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
struct _Ndyn__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ {
nlang_builtins_bool (*has_next)(void *self);
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ (*next)(void *self);
};
struct _Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ {
const struct _Ndyn__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ *vptr;
void *obj;
};
#endif // HAS1__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS1__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS1__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
struct _Ndyn__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ {
nlang_builtins_bool (*has_next)(void *self);
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ (*next)(void *self);
};
struct _Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ {
const struct _Ndyn__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ *vptr;
void *obj;
};
#endif // HAS1__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS1__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS1__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ {
nlang_builtins_valist ap;
nlang_builtins_size n;
}
;
#endif // HAS1__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_



#define NLANG_DECLARE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#define NLANG_DECLARE_FUNCTIONS
# include "t00/optional.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS
#ifndef HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_
static inline nlang_builtins_i32 _Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_(_Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_ opt, nlang_builtins_i32 fallback);
#endif // HAS2__Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_
static nlang_builtins_i32 t00_optional_opts(_Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_ a);

#ifndef HAS2__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
nlang_builtins_bool _Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next(_Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ self);
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__next(_Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ self);
#endif // HAS2__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#endif // HAS2__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef const struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next
#define HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next
static inline nlang_builtins_bool _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next(_Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next
;
#ifndef HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__left
#define HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__left
static inline nlang_builtins_size _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__left(_Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__left
;
#ifndef HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__ctor
#define HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__ctor
static inline nlang_builtins_void _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__ctor
;
#ifndef HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__mk
#define HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__mk
static inline void _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__mk(_Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ *_nrtr_r);
#endif // HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__mk
;
#ifndef HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__new
#define HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__new
static inline _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__new(void);
#endif // HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__new
;
#ifndef HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__copy_ctor
#define HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__copy_ctor
static inline nlang_builtins_void _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__copy_ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ self, _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ other) __attribute__((__nonnull__(1, 2)));
#endif // HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__copy_ctor
;
#endif // HAS2__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
static nlang_builtins_i32 t00_optional_chained(_Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ v) __attribute__((__nonnull__(1)));

static nlang_builtins_i32 t00_optional_var(nlang_builtins_i32 a, _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_ b, nlang_builtins_size _Nvarargcount, ...);

static nlang_builtins_i32 t00_optional_onlyvar(nlang_builtins_size _Nvarargcount, ...);

#define NLANG_DEFINE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#define NLANG_DEFINE_FUNCTIONS
# include "t00/optional.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS
#ifndef HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_
static inline nlang_builtins_i32 _Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_(_Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_ opt, nlang_builtins_i32 fallback) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
 {
( (({ _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_ _Ngensym104 = NULL;
;
nlang_builtins_bool _Ngensym105 = (opt != _Ngensym104);
;
_Ngensym105;
; })) ? ( {
;
nlang_builtins_i32 _Ngensym106 = ((*opt));
;
return _Ngensym106;
})
 : ( {
;
return fallback;
}));
;
;
}
return _nretval;
}
#endif // HAS3__Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_
static nlang_builtins_i32 t00_optional_opts(_Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_ a) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
 {
nlang_builtins_i32 _Ngensym0 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensym1 = _Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_(a, _Ngensym0);
;
return _Ngensym1;
}
return _nretval;
}

#ifndef HAS3__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
nlang_builtins_bool _Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next(_Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ self) {
return self.vptr->has_next(self.obj);
}
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__next(_Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ self) {
return self.vptr->next(self.obj);
}
#endif // HAS3__Ngen_nlang_containers__Ni_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#endif // HAS3__Ngen_nlang_builtins__Ni_no_dyn_iterator___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef const struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next
#define HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next
static inline nlang_builtins_bool _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next(_Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ self) {
#define THIS(x) _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_##x
__attribute__((__unused__)) nlang_builtins_bool _nretval = { 0 };
 {
;;
nlang_builtins_size _Ngensym99 = (nlang_builtins_size)0;
;
nlang_builtins_bool _Ngensym9a = ((self->n) > _Ngensym99);
;
return _Ngensym9a;
}
return _nretval;
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next
;
#ifndef HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__left
#define HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__left
static inline nlang_builtins_size _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__left(_Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ self) {
#define THIS(x) _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_##x
__attribute__((__unused__)) nlang_builtins_size _nretval = { 0 };
 {
;;
return (self->n);
}
return _nretval;
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__left
;
#ifndef HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__ctor
#define HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__ctor
static inline nlang_builtins_void _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ self) {
#define THIS(x) _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_##x
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__ctor
;
#ifndef HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__mk
#define HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__mk
static inline void _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__mk(_Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ *_nrtr_r) {
#define THIS(x) _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_##x
#define r (*_nrtr_r)
#undef r
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__mk
;
#ifndef HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__new
#define HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__new
static inline _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__new(void) {
#define THIS(x) _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_##x
__attribute__((__unused__)) _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ _nretval = { 0 };
return calloc(1, sizeof(THIS()));
return _nretval;
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__new
;
#ifndef HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__copy_ctor
#define HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__copy_ctor
static inline nlang_builtins_void _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__copy_ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ self, _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ other) {
#define THIS(x) _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_##x
memcpy(self, other, sizeof(*self));
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__copy_ctor
;
#endif // HAS3__Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
#define HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_;
typedef struct _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_
static nlang_builtins_i32 t00_optional_chained(_Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ v) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
 {
;;
nlang_builtins_i32 s = (nlang_builtins_i32)0;
;
 {
 {
;;
;;
_Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ _Ngensym2 = ((&((*v))));
;
 {
while (({ nlang_builtins_bool _Ngensym4 = _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next(_Ngensym2);
;
_Ngensym4;
; })) {
;
;
;;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ i = NLANG_BUILTINS_VARARG_NEXT(_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_, *(_Ngensym2));
;
 {
nlang_builtins_i32 _Ngensym5 = ((*i));
;
s += _Ngensym5;
};
};
;
;
};
};
};
;
return s;
}
return _nretval;
}

static nlang_builtins_i32 t00_optional_var(nlang_builtins_i32 a, _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_ b, nlang_builtins_size _Nvarargcount, ...) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
_Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ v = { 0 };
NLANG_BUILTINS_VARARG_START(v);
 {
;;
_Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ _Ngensym6 = ((&v));
;
nlang_builtins_i32 s = t00_optional_chained(_Ngensym6);
;
;
nlang_builtins_i32 _Ngensym7 = (nlang_builtins_i32)0;
;
nlang_builtins_i32 _Ngensym8 = _Ngen_nlang_builtins_optional__nlang_builtins_i32_genN_(b, _Ngensym7);
;
nlang_builtins_i32 _Ngensym9 = (a + _Ngensym8);
;
nlang_builtins_i32 _Ngensyma = (_Ngensym9 + s);
;
return _Ngensyma;
}
NLANG_BUILTINS_VARARG_END(v);
return _nretval;
}

static nlang_builtins_i32 t00_optional_onlyvar(nlang_builtins_size _Nvarargcount, ...) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
_Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN_ v = { 0 };
NLANG_BUILTINS_VARARG_START(v);
 {
;;
nlang_builtins_i32 s = (nlang_builtins_i32)0;
;
 {
 {
;;
_Ngen_nlang_builtins_mutable_ref___Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__genN_ _Ngensymb = ((&v));
;
 {
while (({ nlang_builtins_bool _Ngensymc = _Ngen_nlang_builtins_vararg___Ngen_nlang_builtins_ref__nlang_builtins_i32_genN__genN__has_next(_Ngensymb);
;
_Ngensymc;
; })) {
;
;
;;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ i = NLANG_BUILTINS_VARARG_NEXT(_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_, *(_Ngensymb));
;
 {
nlang_builtins_i32 _Ngensymd = ((*i));
;
s += _Ngensymd;
};
};
;
;
};
};
};
;
return s;
}
NLANG_BUILTINS_VARARG_END(v);
return _nretval;
}

nlang_builtins_i32 _Nmain(void) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
 {
( (({ nlang_builtins_i32 _Ngensyme = (nlang_builtins_i32)1;
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym29 = ((&_Ngensyme));
;
nlang_builtins_i32 _Ngensymf = t00_optional_opts(_Ngensym29);
;
nlang_builtins_i32 _Ngensym10 = (nlang_builtins_i32)1;
;
nlang_builtins_bool _Ngensym11 = (_Ngensymf != _Ngensym10);
;
_Ngensym11;
; })) ? ( {
nlang_builtins_i32 _Ngensym12 = (nlang_builtins_i32)1;
;
return _Ngensym12;
})
 : ( {
;;
}));
( (({ nlang_builtins_i32 _Ngensym13 = (nlang_builtins_i32)1;
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym2a = ((&_Ngensym13));
;
nlang_builtins_i32 _Ngensym14 = t00_optional_opts(_Ngensym2a);
;
_Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_ _Ngensym2b = NULL;
;
nlang_builtins_i32 _Ngensym2c = t00_optional_opts(_Ngensym2b);
;
nlang_builtins_bool _Ngensym15 = (_Ngensym14 != _Ngensym2c);
;
_Ngensym15;
; })) ? ( {
nlang_builtins_i32 _Ngensym16 = (nlang_builtins_i32)1;
;
return _Ngensym16;
})
 : ( {
;;
}));
nlang_builtins_i32 _Ngensym17 = (nlang_builtins_i32)10;
;
nlang_builtins_i32 _Ngensym18 = (nlang_builtins_i32)0;
;
nlang_builtins_i32 _Ngensym19 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensym1a = (nlang_builtins_i32)2;
;
nlang_builtins_i32 _Ngensym1b = (nlang_builtins_i32)3;
;
nlang_builtins_i32 _Ngensym1c = (nlang_builtins_i32)4;
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym2d = ((&_Ngensym19));
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym2e = ((&_Ngensym1a));
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym2f = ((&_Ngensym1b));
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym30 = ((&_Ngensym1c));
;
nlang_builtins_i32 _Ngensym1d = t00_optional_var(_Ngensym18, _Ngensym2d, 3, _Ngensym2e, _Ngensym2f, _Ngensym30);
;
nlang_builtins_bool _Ngensym1e = (_Ngensym17 == _Ngensym1d);
;
nlang_builtins_assert(_Ngensym1e);
nlang_builtins_i32 _Ngensym1f = (nlang_builtins_i32)10;
;
nlang_builtins_i32 _Ngensym20 = (nlang_builtins_i32)0;
;
nlang_builtins_i32 _Ngensym21 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensym22 = (nlang_builtins_i32)2;
;
nlang_builtins_i32 _Ngensym23 = (nlang_builtins_i32)3;
;
nlang_builtins_i32 _Ngensym24 = (nlang_builtins_i32)4;
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym31 = ((&_Ngensym20));
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym32 = ((&_Ngensym21));
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym33 = ((&_Ngensym22));
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym34 = ((&_Ngensym23));
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym35 = ((&_Ngensym24));
;
nlang_builtins_i32 _Ngensym25 = t00_optional_onlyvar(5, _Ngensym31, _Ngensym32, _Ngensym33, _Ngensym34, _Ngensym35);
;
nlang_builtins_bool _Ngensym26 = (_Ngensym1f == _Ngensym25);
;
nlang_builtins_assert(_Ngensym26);
nlang_builtins_i32 _Ngensym27 = (nlang_builtins_i32)0;
;
_Ngen_nlang_builtins_ref__nlang_builtins_i32_genN_ _Ngensym36 = ((&_Ngensym27));
;
nlang_builtins_i32 _Ngensym28 = t00_optional_opts(_Ngensym36);
;
return _Ngensym28;
}
return _nretval;
}
void t00_optional_Nrunexamples(void) __attribute__((section(".text.nlang.examples")));
void t00_optional_Nrunexamples(void) {
}
