#include <lib/nlang/runtime.h>
#define NLANG_DECLARE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_TYPES

#define NLANG_DECLARE_TYPES
# include "t00/tuple.n.o.h"
#undef NLANG_DECLARE_TYPES
#ifndef HAS0__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_;
#ifndef HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
;
#ifndef HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_;
typedef const struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
;
#endif // HAS0__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_


#define NLANG_DEFINE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_TYPES

#define NLANG_DEFINE_TYPES
# include "t00/tuple.n.o.h"
#undef NLANG_DEFINE_TYPES
#ifndef HAS1__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
#define HAS1__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ {
nlang_builtins_i32 x0;
nlang_builtins_i32 x1;
}
;
#endif // HAS1__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_


#define NLANG_DECLARE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#define NLANG_DECLARE_FUNCTIONS
# include "t00/tuple.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS
#ifndef HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__ctor
#define HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__ctor
static inline nlang_builtins_void _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__ctor
;
#ifndef HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__mk
#define HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__mk
static inline _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__mk(void);
#endif // HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__mk
;
#ifndef HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__new
#define HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__new
static inline _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__new(void);
#endif // HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__new
;
#ifndef HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_;
typedef const struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__copy_ctor
#define HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__copy_ctor
static inline nlang_builtins_void _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__copy_ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ self, _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ other) __attribute__((__nonnull__(1, 2)));
#endif // HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__copy_ctor
;
#endif // HAS2__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
static _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ t00_tuple_foo(void);

static _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ t00_tuple_bar(void);

#define NLANG_DEFINE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#define NLANG_DEFINE_FUNCTIONS
# include "t00/tuple.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS
#ifndef HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__ctor
#define HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__ctor
static inline nlang_builtins_void _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_##x
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__ctor
;
#ifndef HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__mk
#define HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__mk
static inline _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__mk(void) {
#define THIS(x) _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_##x
__attribute__((__unused__)) _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ r = { 0 };
return (THIS()){ 0 };
return r;
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__mk
;
#ifndef HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__new
#define HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__new
static inline _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__new(void) {
#define THIS(x) _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_##x
__attribute__((__unused__)) _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ _nretval = { 0 };
return calloc(1, sizeof(THIS()));
return _nretval;
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__new
;
#ifndef HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_;
typedef const struct _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__copy_ctor
#define HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__copy_ctor
static inline nlang_builtins_void _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__copy_ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ self, _Ngen_nlang_builtins_ref___Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__genN_ other) {
#define THIS(x) _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_##x
memcpy(self, other, sizeof(*self));
#undef THIS
}
#endif // HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN__copy_ctor
;
#endif // HAS3__Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_
static _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ t00_tuple_foo(void) {
__attribute__((__unused__)) _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _nretval = { 0 };
 {
nlang_builtins_i32 _Ngensym0 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensym1 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensym2 = (-_Ngensym1);
;
_Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngensym3 = (_Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_){_Ngensym0, _Ngensym2};
;
return _Ngensym3;
}
return _nretval;
}

static _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ t00_tuple_bar(void) {
__attribute__((__unused__)) _Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _nretval = { 0 };
__attribute__((__unused__)) nlang_builtins_i32 x = { 0 };
__attribute__((__unused__)) nlang_builtins_i32 y = { 0 };
 {
nlang_builtins_i32 _Ngensym4 = (nlang_builtins_i32)1;
;
x = _Ngensym4;
;
nlang_builtins_i32 _Ngensym5 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensym6 = (-_Ngensym5);
;
y = _Ngensym6;
}
return _nretval;
}

nlang_builtins_i32 _Nmain(void) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
 {
;;
nlang_builtins_i32 _Ngensym8 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensym9 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensyma = (-_Ngensym9);
;
_Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngensym7 = (_Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_){_Ngensym8, _Ngensyma};
;
nlang_builtins_i32 x0 = (_Ngensym7.x0);
;
nlang_builtins_i32 y0 = (_Ngensym7.x1);
;
;
;;
_Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngensymb = t00_tuple_foo();
;
nlang_builtins_i32 x = (_Ngensymb.x0);
;
nlang_builtins_i32 y = (_Ngensymb.x1);
;
nlang_builtins_i32 _Ngensymc = (x0 * y0);
;
nlang_builtins_i32 _Ngensymd = (_Ngensymc * x);
;
nlang_builtins_i32 _Ngensyme = (_Ngensymd * y);
;
nlang_builtins_i32 _Ngensymf = (nlang_builtins_i32)1;
;
nlang_builtins_bool _Ngensym10 = (_Ngensyme == _Ngensymf);
;
nlang_builtins_assert(_Ngensym10);
;;
_Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngensym11 = t00_tuple_foo();
;
nlang_builtins_i32 x1 = (_Ngensym11.x0);
;
(void) (_Ngensym11.x1);
;;
_Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngensym12 = t00_tuple_foo();
;
(void) (_Ngensym12.x0);
nlang_builtins_i32 y1 = (_Ngensym12.x1);
;
;;
_Ngen_nlang_builtins_tuple_2__nlang_builtins_i32__nlang_builtins_i32_genN_ _Ngensym13 = t00_tuple_bar();
;
nlang_builtins_i32 x2 = (_Ngensym13.x0);
;
nlang_builtins_i32 y2 = (_Ngensym13.x1);
;
nlang_builtins_i32 _Ngensym14 = (x2 + y2);
;
nlang_builtins_i32 _Ngensym15 = (nlang_builtins_i32)0;
;
nlang_builtins_bool _Ngensym16 = (_Ngensym14 == _Ngensym15);
;
nlang_builtins_assert(_Ngensym16);
nlang_builtins_i32 _Ngensym17 = (x0 + y0);
;
nlang_builtins_i32 _Ngensym18 = (x + y);
;
nlang_builtins_i32 _Ngensym19 = (_Ngensym17 + _Ngensym18);
;
nlang_builtins_i32 _Ngensym1a = (x1 + y1);
;
nlang_builtins_i32 _Ngensym1b = (_Ngensym19 + _Ngensym1a);
;
return _Ngensym1b;
}
return _nretval;
}
void t00_tuple_Nrunexamples(void) __attribute__((section(".text.nlang.examples")));
void t00_tuple_Nrunexamples(void) {
}
