#!/usr/bin/env bash

list=$*
if [ -z "$list" ]; then
	list=t[0-9][0-9]/*.n
fi

for t in $list; do
	for all in stderr tree pretty c; do
		if [ -f $t.$all.out ]; then
			cp -p $t.$all.out $t.$all.ref
			git add $t.$all.ref
		else
			if rm $t.$all.ref 2> /dev/null; then
				git rm $t.$all.ref
			fi
		fi
	done
done
