#!/usr/bin/env bash

list=$*
if [ -z "$list" ]; then
	list=t[0-9][0-9]/*.n
fi

for t in $list; do
	for all in stderr stdout tree pretty c; do
		if [ -f $t.o.$all ]; then
			cp -p $t.o.$all $t.ref.$all
			if [[ "$all" =~ ^(stderr|stdout)$ ]]; then
				git add $t.ref.$all
			fi
		else
			if rm $t.ref.$all 2> /dev/null; then
				git rm $t.ref.$all
			fi
		fi
	done
done
