#!/usr/bin/env bash

wd=$(dirname $0)
WD="$wd/"
if [ "$WD" == "./" ]; then
	WD=""
fi

list=$*
if [ -z "$list" ]; then
	list=$(find ${WD}t[0-9][0-9] -name \*.n |sort -u)
fi
list=$(echo $list |perl -pe 's/\S+?\W?skipped_\S+//g')

ret=0

if [ -z "$TDIFF_WHAT" ]; then
	TDIFF_WHAT="status stderr stdout tree pretty c"
fi

if [ -f "$t.ref.go" ] && [ -f "$t.ref.stdout" ]; then
	echo "Invalid test $t: cannot have both $t.ref.go and $t.ref.stdout"
fi

for t in $list; do
	for all in $TDIFF_WHAT; do
		if [ -f $t.ref.$all ] || [ -f $t.o.$all ]; then
			ref=$t.ref.$all
			if [ "$all" = "stdout" ] && [ -f $t.ref.go ]; then
				ref=$t.o.ref.go
				go run $t.ref.go > $ref
			fi

			if ! cmp -s $ref $t.o.$all; then
				ret=1
				need_hr=1
				echo "FAILED $t: different output '$all' from '$ref'"
				diff -Nu $ref $t.o.$all
			fi
		fi
	done

	if (( $need_hr )); then
		echo "---------------------------------------------------------------"
	fi
done

exit $ret
