#!/bin/bash

WD="$(dirname $0)/"
if [ "$WD" == "./" ]; then
	WD=""
fi

list=$*
if [ -z "$list" ]; then
	list=${WD}t/[0-9][0-9]/*.n
fi

for t in $list; do
	rm -f $t.*.out
	if [ -f $t.stderr ]; then
		if ${WD}bootstrap/0/ncc0 $t 2> $t.stderr.out; then
			echo "FAILED $t: did not fail"
		fi
	else
		if ! ${WD}bootstrap/0/ncc0 $t 2> $t.stderr.out; then
			echo "FAILED $t: did not succeed"
			cat $t.stderr.out
		fi
		if ! [ -s $t.stderr.out ]; then
			# Remove empty.
			rm $t.stderr.out
		fi
	fi
	for all in stderr tree pretty; do
		if [ -f $t.$all ] || [ -f $t.$all.out ]; then
			if ! cmp -s $t.$all $t.$all.out; then
				echo "FAILED $t: different output '$all'"
				diff -u $t.$all $t.$all.out
			fi
		fi
	done
done
