#!/usr/bin/env bash

wd=$(dirname $0)
WD="$wd/"
if [ "$WD" == "./" ]; then
	WD=""
fi

list=$*
if [ -z "$list" ]; then
	list=${WD}t[0-9][0-9]/*.n
fi

ret=0

function build_and_run() {
  $wd/ncc0 $1 2> $1.stderr.out \
	  && ./a.out > $1.stdout.out 2>> $1.stderr.out
}

for t in $list; do
	rm -f $t.*.out
	# Assume that having a .stderr.ref file means the test should fail.
	if [ -f $t.stderr.ref ]; then
		if build_and_run $t; then
			echo "FAILED $t: did not fail"
			ret=1
			if ! [ -s $t.stderr.out ]; then
				# Remove empty.
				rm $t.stderr.out
			fi
		fi
	else
		if ! build_and_run $t; then
			echo "FAILED $t: did not succeed"
			ret=1
		fi
		if ! [ -s $t.stderr.out ]; then
			# Remove empty.
			rm $t.stderr.out
		fi
	fi

	if ! [ -s $t.stdout.out ]; then
		# Remove empty.
		rm -f $t.stdout.out
	fi

	if [ -s $t.stderr.out ]; then
		perl -i -ne 'if (!m/^\tE: /) { print; }' $t.stderr.out
	fi

	for all in stderr stdout tree pretty c; do
		if [ -f $t.$all.ref ] || [ -f $t.$all.out ]; then
			if ! cmp -s $t.$all.ref $t.$all.out; then
				ret=1
				echo "FAILED $t: different output '$all'"
				if [[ "$all" = "stderr" || "$all" = "stdout" ]]; then
					diff -Nu $t.$all.ref $t.$all.out
				fi
			fi
		fi
	done
done

exit $ret
