#!/usr/bin/env bash

set -e

cd $(dirname $0)

re2c -b -o lexer.c lexer.re

CFLAGS="-std=c99 -Wall -O0
  -Wmissing-prototypes -Wpointer-arith -Wstrict-prototypes
  -Wmissing-declarations -Wno-format-zero-length -Wbad-function-cast
  -Wcast-align -Wwrite-strings"

gcc -g $CFLAGS -o ncc0 ncc0.c common.c lexer.c \
	parser0.c firstpass0.c \
	printer0.c printer_c0.c \
	hash.c bitops.c
