#ifndef PRINTER_H__
#define PRINTER_H__

#include "common.h"
#include "parser.h"

error printer_pretty(int fd, const struct module *mod);

static const char *tokens_string[TOKEN__NUM] = {
  [Timport] = "import",
  [Texport] = "export",
  [Tfrom] = "from",
  [Ttype] = "type",
  [Textern] = "extern",
  [Tfun] = "fun",
  [Tmethod] = "method",
  [Tunion] = "union",
  [Tintf] = "intf",
  [Tinline] = "inline",
  [Tlet] = "let",
  [Tdyn] = "dyn",
  [Tif] = "if",
  [Telif] = "elif",
  [Telse] = "else",
  [Tfor] = "for",
  [Tin] = "in",
  [Twhile] = "while",
  [Tcontinue] = "continue",
  [Tbreak] = "break",
  [Tmatch] = "match",
  [Treturn] = "return",
  [Ttry] = "try",
  [Tcatch] = "catch",
  [Texcept] = "except",
  [Tthrow] = "throw",
  [Tblock] = "block",
  [Tdelegate] = "delegate",
  [Tdeclare] = "declare",
  [Tand] = " and ",
  [Tor] = " or ",
  [Tnot] = "not",
  [Tisa] = " isa ",
  [Tnull] = "null",
  [Tpass] = "pass",
  [Tpre] = "pre",
  [Tpost] = "post",
  [Tinvariant] = "invariant",
  [Texample] = "example",

  [TASSIGN] = " = ",
  [TEQ] = " == ",
  [TNE] = " != ",
  [TLE] = " <= ",
  [TLT] = " < ",
  [TGT] = " > ",
  [TGE] = " >= ",
  [TPLUS] = " + ",
  [TMINUS] = " - ",
  [TUPLUS] = "+",
  [TUMINUS] = "-",
  [TTIMES] = " * ",
  [TDIVIDE] = " / ",
  [TMODULO] = " % ",
  [TBWAND] = " & ",
  [TBWOR] = " | ",
  [TBWXOR] = " ^ ",
  [TRSHIFT] = " >> ",
  [TLSHIFT] = " << ",
  [TPLUS_ASSIGN] = " += ",
  [TMINUS_ASSIGN] = " -= ",
  [TTIMES_ASSIGN] = " *= ",
  [TDIVIDE_ASSIGN] = " /= ",
  [TMODULO_ASSIGN] = " %= ",
  [TBWAND_ASSIGN] = " &= ",
  [TBWOR_ASSIGN] = " |= ",
  [TBWXOR_ASSIGN] = " ^= ",
  [TRSHIFT_ASSIGN] = " >>= ",
  [TLSHIFT_ASSIGN] = " <<= ",
  [TUBWNOT] = " ~",
  [TARROW] = " -> ",
  [TCOLON] = ":",
  [TCOMMA] = ", ",
  [TSEMICOLON] = "; ",
  [TDOT] = ".",
  [TBANG] = "!",
  [TSHARP] = "#",
  [TREFDOT] = "@",
  [TREFBANG] = "@!",
  [TREFSHARP] = "@#",
  [TNULREFDOT] = "?@",
  [TNULREFBANG] = "?@!",
  [TNULREFSHARP] = "?@#",
  [TDOTDOTDOT] = "...",
  [TSLICEBRAKETS] = "[]",
  [TLINIT] = "{{",
  [TRINIT] = "}}",
  [TLPAR] = "(",
  [TRPAR] = ")",
};

#endif
