#include <lib/nlang/runtime.h>
#define NLANG_DECLARE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_TYPES

#define NLANG_DECLARE_TYPES
# include "t01/generic.n.o.h"
#undef NLANG_DECLARE_TYPES

#ifndef HAS0__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#define HAS0__Ngen_t01_generic_container__nlang_builtins_i32_genN_
struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_ _Ngen_t01_generic_container__nlang_builtins_i32_genN_;
#ifndef HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
;
#endif // HAS0__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#define NLANG_DEFINE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_TYPES

#define NLANG_DEFINE_TYPES
# include "t01/generic.n.o.h"
#undef NLANG_DEFINE_TYPES

#ifndef HAS1__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#define HAS1__Ngen_t01_generic_container__nlang_builtins_i32_genN_
struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_ {
nlang_builtins_i32 x;
}
;
#endif // HAS1__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#define NLANG_DECLARE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#define NLANG_DECLARE_FUNCTIONS
# include "t01/generic.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#ifndef HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#define HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__ctor
#define HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__ctor
nlang_builtins_void _Ngen_t01_generic_container__nlang_builtins_i32_genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__ctor
;
#ifndef HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__mk
#define HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__mk
void _Ngen_t01_generic_container__nlang_builtins_i32_genN__mk(_Ngen_t01_generic_container__nlang_builtins_i32_genN_ *_nrtr_r);
#endif // HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__mk
;
#ifndef HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__new
#define HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__new
_Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_ _Ngen_t01_generic_container__nlang_builtins_i32_genN__new(void);
#endif // HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN__new
;
#endif // HAS2__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#define NLANG_DEFINE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#define NLANG_DEFINE_FUNCTIONS
# include "t01/generic.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#ifndef HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#define HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_generic_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__ctor
#define HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__ctor
nlang_builtins_void _Ngen_t01_generic_container__nlang_builtins_i32_genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_t01_generic_container__nlang_builtins_i32_genN_##x
#undef THIS
}
#endif // HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__ctor
;
#ifndef HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__mk
#define HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__mk
void _Ngen_t01_generic_container__nlang_builtins_i32_genN__mk(_Ngen_t01_generic_container__nlang_builtins_i32_genN_ *_nrtr_r) {
#define THIS(x) _Ngen_t01_generic_container__nlang_builtins_i32_genN_##x
#define r (*_nrtr_r)
#undef r
#undef THIS
}
#endif // HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__mk
;
#ifndef HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__new
#define HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__new
_Ngen_nlang_builtins_mercurial_ref___Ngen_t01_generic_container__nlang_builtins_i32_genN__genN_ _Ngen_t01_generic_container__nlang_builtins_i32_genN__new(void) {
#define THIS(x) _Ngen_t01_generic_container__nlang_builtins_i32_genN_##x
return calloc(1, sizeof(THIS()));
#undef THIS
}
#endif // HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN__new
;
#endif // HAS3__Ngen_t01_generic_container__nlang_builtins_i32_genN_
nlang_builtins_i32 _Nmain(void) {
 {
_Ngen_t01_generic_container__nlang_builtins_i32_genN_ v= { 0 };
v.x = (nlang_builtins_i32)1;
;
;
return ((v.x) - (nlang_builtins_i32)1);
}
}
void t01_generic_Nrunexamples(void) __attribute__((section(".text.nlang.examples")));
void t01_generic_Nrunexamples(void) {
}
