#include <lib/nlang/runtime.h>
#define NLANG_DECLARE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_TYPES

#define NLANG_DECLARE_TYPES
# include "t01/genericsum.n.o.h"
#undef NLANG_DECLARE_TYPES

#ifndef HAS0__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#define HAS0__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_ _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_;
#ifndef HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
;
#ifndef HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
;
#endif // HAS0__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#define NLANG_DEFINE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_TYPES

#define NLANG_DEFINE_TYPES
# include "t01/genericsum.n.o.h"
#undef NLANG_DEFINE_TYPES

#ifndef HAS1__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#define HAS1__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_ {
nlang_builtins_i32 x;
}
;
#endif // HAS1__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#define NLANG_DECLARE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#define NLANG_DECLARE_FUNCTIONS
# include "t01/genericsum.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#ifndef HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#define HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add
#define HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add
nlang_builtins_void _Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add(_Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_ self, nlang_builtins_i32 x) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add
;
#ifndef HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__ctor
#define HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__ctor
nlang_builtins_void _Ngen_t01_genericsum_container__nlang_builtins_i32_genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__ctor
;
#ifndef HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__mk
#define HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__mk
void _Ngen_t01_genericsum_container__nlang_builtins_i32_genN__mk(_Ngen_t01_genericsum_container__nlang_builtins_i32_genN_ *_nrtr_r);
#endif // HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__mk
;
#ifndef HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__new
#define HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__new
_Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_ _Ngen_t01_genericsum_container__nlang_builtins_i32_genN__new(void);
#endif // HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__new
;
#endif // HAS2__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#define NLANG_DEFINE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#define NLANG_DEFINE_FUNCTIONS
# include "t01/genericsum.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#ifndef HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#define HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add
#define HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add
nlang_builtins_void _Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add(_Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_ self, nlang_builtins_i32 x) {
#define THIS(x) _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_##x
 {
;;
(self->x) += x;
}
#undef THIS
}
#endif // HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add
;
#ifndef HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_;
typedef struct _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__ctor
#define HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__ctor
nlang_builtins_void _Ngen_t01_genericsum_container__nlang_builtins_i32_genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_##x
#undef THIS
}
#endif // HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__ctor
;
#ifndef HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__mk
#define HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__mk
void _Ngen_t01_genericsum_container__nlang_builtins_i32_genN__mk(_Ngen_t01_genericsum_container__nlang_builtins_i32_genN_ *_nrtr_r) {
#define THIS(x) _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_##x
#define r (*_nrtr_r)
#undef r
#undef THIS
}
#endif // HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__mk
;
#ifndef HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__new
#define HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__new
_Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_ _Ngen_t01_genericsum_container__nlang_builtins_i32_genN__new(void) {
#define THIS(x) _Ngen_t01_genericsum_container__nlang_builtins_i32_genN_##x
__attribute__((__unused__)) _Ngen_nlang_builtins_mercurial_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_ _nretval = { 0 };
return calloc(1, sizeof(THIS()));
return _nretval;
#undef THIS
}
#endif // HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN__new
;
#endif // HAS3__Ngen_t01_genericsum_container__nlang_builtins_i32_genN_
nlang_builtins_i32 _Nmain(void) {
__attribute__((__unused__)) nlang_builtins_i32 _nretval = { 0 };
 {
;;
nlang_builtins_i32 _Ngensym1 = (nlang_builtins_i32)0;
;
_Ngen_t01_genericsum_container__nlang_builtins_i32_genN_ v= { 0 };
v.x = _Ngensym1;
;
;
;
;
 {
nlang_builtins_i32 _Ngensym2 = (nlang_builtins_i32)1;
;
_Ngen_nlang_builtins_mutable_ref___Ngen_t01_genericsum_container__nlang_builtins_i32_genN__genN_ _Ngensymb = ((&v));
;
;;
_Ngen_t01_genericsum_container__nlang_builtins_i32_genN__add(_Ngensymb, _Ngensym2);
};
;
;
;;
nlang_builtins_i32 _Ngensym6 = (nlang_builtins_i32)1;
;
nlang_builtins_i32 _Ngensym7 = ((v.x) - _Ngensym6);
;
return _Ngensym7;
}
return _nretval;
}
void t01_genericsum_Nrunexamples(void) __attribute__((section(".text.nlang.examples")));
void t01_genericsum_Nrunexamples(void) {
}
