#include <lib/nlang/runtime.h>
#define NLANG_DECLARE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_TYPES

#define NLANG_DECLARE_TYPES
# include "lib/nlang/sysheap.n.o.h"
#undef NLANG_DECLARE_TYPES

#define NLANG_DECLARE_TYPES
# include "t02/slice.n.o.h"
#undef NLANG_DECLARE_TYPES
#ifndef HAS0__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
#define HAS0__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
typedef nlang_builtins_u8* _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_;
#endif // HAS0__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
#ifndef HAS0__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
#ifndef HAS0__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_ _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
#ifndef HAS0__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
;
#ifndef HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef const struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
;
#ifndef HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#ifndef HAS0__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
#define HAS0__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
typedef const nlang_builtins_u8* _Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_;
#endif // HAS0__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
;
#endif // HAS0__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#ifndef HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#ifndef HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS0__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#ifndef HAS0__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#define HAS0__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_;
#endif // HAS0__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#ifndef HAS0__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
#define HAS0__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
struct nlang_sysheap_heap;
typedef struct nlang_sysheap_heap* _Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_;
#endif // HAS0__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
#define NLANG_DEFINE_TYPES
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_TYPES

#define NLANG_DEFINE_TYPES
# include "lib/nlang/sysheap.n.o.h"
#undef NLANG_DEFINE_TYPES

#define NLANG_DEFINE_TYPES
# include "t02/slice.n.o.h"
#undef NLANG_DEFINE_TYPES
#ifndef HAS1__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#define HAS1__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_ {
_Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_ d;
nlang_builtins_size c;
}
;
#endif // HAS1__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#define NLANG_DECLARE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#define NLANG_DECLARE_FUNCTIONS
# include "lib/nlang/sysheap.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS

#define NLANG_DECLARE_FUNCTIONS
# include "t02/slice.n.o.h"
#undef NLANG_DECLARE_FUNCTIONS
#ifndef HAS2__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
#define HAS2__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
typedef nlang_builtins_u8* _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_;
#endif // HAS2__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
#ifndef HAS2__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_wrap
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_wrap
static inline nlang_builtins_void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_wrap(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self, _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_ data, nlang_builtins_size count) __attribute__((__nonnull__(1, 2)));
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_wrap
;
#ifndef HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef const struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count
static inline nlang_builtins_size _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count(_Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count
;
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount
static inline nlang_builtins_size _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount(_Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount
;
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__all
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__all
static inline nlang_containers_index_range _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__all(_Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__all
;
#ifndef HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
#define HAS2__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
typedef const nlang_builtins_u8* _Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_;
#endif // HAS2__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
#ifndef HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_
#define HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_
static inline _Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_ _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_(_Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_
#ifndef HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_
#define HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_
static inline _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_ _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy
static inline nlang_builtins_void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self, nlang_builtins_size at, _Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ other, nlang_builtins_size off, nlang_builtins_size count) __attribute__((__nonnull__(1, 3)));
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy
;
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__ctor
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__ctor
static inline nlang_builtins_void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__ctor
;
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk
static inline void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk(_Ngen_nlang_memory_slice__nlang_builtins_i32_genN_ *_nrtr_r);
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk
;
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__new
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__new
static inline _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__new(void);
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__new
;
#ifndef HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy_ctor
#define HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy_ctor
static inline nlang_builtins_void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy_ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self, _Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ other) __attribute__((__nonnull__(1, 2)));
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy_ctor
;
#endif // HAS2__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS2__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#ifndef HAS2__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_;
#endif // HAS2__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#ifndef HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_
#define HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_
static inline _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_ _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_(_Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self, nlang_builtins_size n) __attribute__((__nonnull__(1)));
#endif // HAS2__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_
#ifndef HAS2__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
#define HAS2__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
struct nlang_sysheap_heap;
typedef struct nlang_sysheap_heap* _Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_;
#endif // HAS2__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
#ifndef HAS2__Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_
#define HAS2__Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_
static inline nlang_builtins_void _Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_(_Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_ self, _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ s, nlang_builtins_size count) __attribute__((__nonnull__(1, 2)));
#endif // HAS2__Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_
#define NLANG_DEFINE_FUNCTIONS
# include "lib/nlang/module.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#define NLANG_DEFINE_FUNCTIONS
# include "lib/nlang/sysheap.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS

#define NLANG_DEFINE_FUNCTIONS
# include "t02/slice.n.o.h"
#undef NLANG_DEFINE_FUNCTIONS
#ifndef HAS3__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
#define HAS3__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
typedef nlang_builtins_u8* _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_;
#endif // HAS3__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_
#ifndef HAS3__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_wrap
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_wrap
static inline nlang_builtins_void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_wrap(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self, _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_i32_genN_ data, nlang_builtins_size count) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
 {
(self->d) = data;
(self->c) = count;
}
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_wrap
;
#ifndef HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef const struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count
static inline nlang_builtins_size _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count(_Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
 {
return (self->c);
}
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count
;
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount
static inline nlang_builtins_size _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount(_Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
 {
return ((self->c) * sizeof(nlang_builtins_i32));
}
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount
;
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__all
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__all
static inline nlang_containers_index_range _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__all(_Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
 {
return nlang_containers_range((nlang_builtins_size)0, (self->c));
}
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__all
;
#ifndef HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
typedef const nlang_builtins_i32* _Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_nullable_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
#define HAS3__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
typedef const nlang_builtins_u8* _Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_;
#endif // HAS3__Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_
#ifndef HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_
#define HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_
static inline _Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_ _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_(_Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
 {
nlang_builtins_assert(((self->c) != (nlang_builtins_size)0));
return (_Ngen_nlang_builtins_ref__nlang_builtins_u8_genN_)((self->d));
}
#undef THIS
}
#endif // HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_
#ifndef HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_
#define HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_
static inline _Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_ _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
 {
nlang_builtins_assert(((self->c) != (nlang_builtins_size)0));
return (_Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_)((self->d));
}
#undef THIS
}
#endif // HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy
static inline nlang_builtins_void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self, nlang_builtins_size at, _Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ other, nlang_builtins_size off, nlang_builtins_size count) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
 {
nlang_builtins_assert(((off + count) <= _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count(other)));
nlang_builtins_assert(((at + count) <= _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count(self)));
nlang_builtins_size bat = (at * sizeof(nlang_builtins_i32));
;
nlang_builtins_size boff = (off * sizeof(nlang_builtins_i32));
;
nlang_builtins_size bsz = (count * sizeof(nlang_builtins_i32));
;
nlang_memory_slice_memcpy(_Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_(self), bat, _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_ref_genN_(other), boff, bsz);
}
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy
;
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__ctor
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__ctor
static inline nlang_builtins_void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__ctor
;
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk
static inline void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk(_Ngen_nlang_memory_slice__nlang_builtins_i32_genN_ *_nrtr_r) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
#define r (*_nrtr_r)
#undef r
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk
;
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__new
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__new
static inline _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__new(void) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
return calloc(1, sizeof(THIS()));
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__new
;
#ifndef HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy_ctor
#define HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy_ctor
static inline nlang_builtins_void _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy_ctor(_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self, _Ngen_nlang_builtins_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ other) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
memcpy(self, other, sizeof(*self));
#undef THIS
}
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__copy_ctor
;
#endif // HAS3__Ngen_nlang_memory_slice__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#define HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_;
typedef struct _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_* _Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_;
#endif // HAS3__Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_
#ifndef HAS3__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
typedef nlang_builtins_i32* _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_;
#endif // HAS3__Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_
#ifndef HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_
#define HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_
static inline _Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_ _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_(_Ngen_nlang_builtins_mutable_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ self, nlang_builtins_size n) {
#define THIS(x) _Ngen_nlang_memory_slice__nlang_builtins_i32_genN_##x
 {
nlang_builtins_assert((n < (self->c)));
nlang_builtins_size off = (n * sizeof(nlang_builtins_i32));
;
_Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_ p = nlang_memory_slice_at_byte(_Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_((_Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_)(self)), off);
;
return (_Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_)(p);
}
#undef THIS
}
#endif // HAS3__Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_
#ifndef HAS3__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
#define HAS3__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
struct nlang_sysheap_heap;
typedef struct nlang_sysheap_heap* _Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_;
#endif // HAS3__Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_
#ifndef HAS3__Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_
#define HAS3__Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_
static inline nlang_builtins_void _Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_(_Ngen_nlang_builtins_mutable_ref__nlang_sysheap_heap_genN_ self, _Ngen_nlang_builtins_mercurial_ref___Ngen_nlang_memory_slice__nlang_builtins_i32_genN__genN_ s, nlang_builtins_size count) {
#define THIS(x) nlang_sysheap_heap##x
 {
nlang_builtins_size bsz = (count * sizeof(nlang_builtins_i32));
;
( ((_Ngen_nlang_memory_slice__nlang_builtins_i32_genN__count(s) == (nlang_builtins_size)0)) ? ( {
(s->d) = (_Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_)(nlang_sysheap_realloc(NULL, (nlang_builtins_size)0, bsz));
(s->c) = count;
})
 : ( {
nlang_builtins_size old_bsz = _Ngen_nlang_memory_slice__nlang_builtins_i32_genN__bytecount(s);
;
_Ngen_nlang_builtins_mercurial_ref__nlang_builtins_u8_genN_ raw = _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__unsafe_rawdata__nlang_builtins_mercurial_ref_genN_(s);
;
(s->d) = (_Ngen_nlang_builtins_nullable_mercurial_ref__nlang_builtins_i32_genN_)(nlang_sysheap_realloc(raw, old_bsz, bsz));
(s->c) = count;
}));
}
#undef THIS
}
#endif // HAS3__Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_
nlang_builtins_i32 _Nmain(void) {
 {
_Ngen_nlang_memory_slice__nlang_builtins_i32_genN_ s = { 0 };
_Ngen_nlang_memory_slice__nlang_builtins_i32_genN__mk(&(s));
_Ngen_nlang_sysheap_heap_slice_realloc__nlang_builtins_i32_genN_(((&nlang_sysheap_sysheap)), ((&s)), (nlang_builtins_size)1);
;
_Ngen_nlang_builtins_mutable_ref__nlang_builtins_i32_genN_ p = _Ngen__Ngen_nlang_memory_slice__nlang_builtins_i32_genN__at__nlang_builtins_mutable_ref_genN_(((&s)), (nlang_builtins_size)0);
;
((*p)) = (nlang_builtins_i32)1;
return (((*p)) - (nlang_builtins_i32)1);
}
}
void t02_slice_Nrunexamples(void) __attribute__((section(".text.nlang.examples")));
void t02_slice_Nrunexamples(void) {
}
